import assert from "node:assert/strict";
import test from "node:test";
import { renderToStaticMarkup } from "react-dom/server";
import { HelpScreen } from "./HelpScreen.tsx";

test("renders scroll stories for active recall and spaced repetition", () => {
  const markup = renderToStaticMarkup(<HelpScreen />);

  assert.match(markup, /Wie CoRe dein Lernen stärkt/);
  assert.match(markup, /Wir wollen Lernen verbessern/);
  assert.match(markup, /Welche Grundsätze nutzt CoRe, um das Lernen möglichst nachhaltig zu gestalten/);
  assert.match(markup, /Active Recall <span class="text-core-warning">→<\/span> Smarter Recall/);
  assert.match(markup, /Spaced Repetition <span class="text-core-warning">→<\/span> Content Repetition/);
  assert.match(markup, /id="active-recall-heading"[^>]*>Active Recall<\/h2>/);
  assert.doesNotMatch(markup, /Active Recall hält den Fokus auf dem Inhalt/);
  assert.doesNotMatch(markup, /Eine Antwort, wechselnde Abrufreize/);
  assert.match(markup, /data-active-recall-card="stack"/);
  assert.match(markup, /Welcher Teil des autonomen<\/span> Nervensystems ist in erster Linie dafür verantwortlich/);
  assert.match(markup, /Je vertrauter die Kartenform wird, desto schwächer wird der aktive Abruf des Inhalts/);
  assert.match(markup, /CoRe verändert die Frage, nicht das Wissen/);
  assert.match(markup, /jedes Mal erneut aktiv abrufst – Smarter Recall/);
  assert.match(markup, /Spaced Repetition findet den passenden Zeitpunkt/);
  assert.match(markup, /Das Diagramm bleibt stehen/);
  assert.match(markup, /So arbeitet ein Spaced-Repetition-Scheduler/);
  assert.match(markup, /alle Reviews einschließlich mehrerer Abrufe am selben Tag/);
  assert.match(markup, /21 Modellparameter/);
  assert.match(markup, /offiziellen 21 Standardparametern/);
  assert.match(markup, /persönliche Optimierung der Parameter[^.]+noch nicht aktiviert/);
  assert.match(markup, /zweiten Kontakt nach 15 Minuten/);
  assert.match(markup, /höhere Zielerinnerung bedeutet kürzere Intervalle und mehr Reviews pro Tag/);
  assert.match(markup, /bereit für Varianten/);
  assert.match(markup, /keine garantierte Reviewnummer/);
  assert.match(markup, /Abrufwahrscheinlichkeit/);
  assert.match(markup, /Stabilität/);
  assert.match(markup, /Schwierigkeit/);
  assert.match(markup, /Zielerinnerung/);
  assert.match(markup, /Ausschnitt 90–100 %/);
  assert.match(markup, /Zwei diagonale Striche/);
  assert.match(markup, /Vereinfachtes Beispiel/);
  assert.match(markup, /1 · Erste Wiederholung/);
  assert.match(markup, /2 · Wiederholung mit Variante/);
  assert.match(markup, /Nochmal · S sehr kurz/);
  assert.match(markup, /Schwer · S kurz/);
  assert.match(markup, /Gut · S länger/);
  assert.match(markup, /Leicht · S am längsten/);
  assert.match(markup, /keine garantierte Produktionsschwelle/);
  assert.match(markup, /href="https:\/\/github\.com\/open-spaced-repetition\/awesome-fsrs\/wiki\/ABC-of-FSRS"/);
  assert.equal((markup.match(/xl:sticky/g) ?? []).length, 2);
  assert.equal((markup.match(/data-testid="active-recall-step-/g) ?? []).length, 3);
  assert.equal((markup.match(/data-testid="spaced-repetition-step-/g) ?? []).length, 10);
  assert.equal((markup.match(/data-story-step=/g) ?? []).length, 13);
  assert.equal((markup.match(/data-testid="memory-parameter-/g) ?? []).length, 3);
  assert.equal((markup.match(/data-testid="memory-review-point-/g) ?? []).length, 2);
  assert.equal((markup.match(/data-testid="memory-rating-path-/g) ?? []).length, 4);
  assert.equal((markup.match(/data-testid="memory-y-axis-break"/g) ?? []).length, 1);
});
