import assert from "node:assert/strict";
import test from "node:test";
import { renderToStaticMarkup } from "react-dom/server";
import { HelpScreen } from "./HelpScreen.tsx";

test("renders scroll stories for active recall and spaced repetition", () => {
  const markup = renderToStaticMarkup(<HelpScreen />);

  assert.match(markup, /Wie CoRe dein Lernen stärkt/);
  assert.match(markup, /Wir wollen Lernen verbessern/);
  assert.match(markup, /Welche <mark class="core-help-keyword">Grundsätze<\/mark> <mark class="core-help-keyword">nutzt CoRe<\/mark>, um das <mark class="core-help-keyword">Lernen<\/mark> möglichst <mark class="core-help-keyword">nachhaltig zu gestalten<\/mark>/);
  assert.equal((markup.match(/class="core-help-keyword"/g) ?? []).length, 4);
  assert.equal((markup.match(/data-testid="help-intro-card-layer"/g) ?? []).length, 2);
  assert.match(markup, /data-testid="help-intro-card-front"/);
  assert.match(markup, /core-help-stack-layer-back/);
  assert.match(markup, /core-help-stack-layer-middle/);
  assert.match(markup, /translate\(-30px, -57px\) scale\(0\.94\)/);
  assert.match(markup, /translate\(-12px, -31px\) scale\(0\.97\)/);
  assert.match(markup, /class="[^"]*bg-core-surface[^"]*"[^>]*data-testid="help-intro-card-front"/);
  assert.equal((markup.match(/core-help-stack-card/g) ?? []).length, 3);
  assert.match(markup, /Active Recall <span class="text-core-warning">→<\/span> Smarter Recall/);
  assert.match(markup, /Spaced Repetition <span class="text-core-warning">→<\/span> Content Repetition/);
  assert.match(markup, /href="#active-recall-heading"/);
  assert.match(markup, /href="#spaced-repetition-heading"/);
  assert.equal((markup.match(/hover:border-t-4/g) ?? []).length, 2);
  assert.equal((markup.match(/focus-visible:border-t-4/g) ?? []).length, 2);
  assert.match(markup, /id="active-recall-heading"[^>]*>Active Recall<\/h2>/);
  assert.doesNotMatch(markup, /Active Recall hält den Fokus auf dem Inhalt/);
  assert.doesNotMatch(markup, /Eine Antwort, wechselnde Abrufreize/);
  assert.match(markup, /data-active-recall-card="stack"/);
  assert.match(markup, /Welcher Teil des autonomen<\/span> <span data-recall-question-body="true">Nervensystems ist in erster Linie dafür verantwortlich/);
  assert.match(markup, /data-testid="active-recall-question"/);
  assert.match(markup, /data-testid="active-recall-question-suffix"/);
  assert.match(markup, /data-testid="active-recall-divider"/);
  assert.match(markup, /data-testid="active-recall-answer"/);
  assert.match(markup, /Je vertrauter die Kartenform wird, desto schwächer wird der aktive Abruf des Inhalts/);
  assert.match(markup, /CoRe verändert die Frage, nicht das Wissen/);
  assert.match(markup, /jedes Mal erneut aktiv abrufst – Smarter Recall/);
  assert.match(markup, /Spaced Repetition findet den passenden Zeitpunkt/);
  assert.match(markup, /Das Diagramm bleibt stehen/);
  assert.match(markup, /So arbeitet ein Spaced-Repetition-Scheduler/);
  assert.match(markup, /alle Reviews einschließlich mehrerer Abrufe am selben Tag/);
  assert.match(markup, /21 Modellparameter/);
  assert.match(markup, /offiziellen 21 Standardparametern/);
  assert.match(markup, /persönliche Optimierung der Parameter[^.]+noch nicht aktiviert/);
  assert.match(markup, /zweiten Kontakt nach 15 Minuten/);
  assert.match(markup, /höhere Zielerinnerung bedeutet kürzere Intervalle und mehr Reviews pro Tag/);
  assert.match(markup, /bereit für Varianten/);
  assert.match(markup, /keine garantierte Reviewnummer/);
  assert.match(markup, /Abrufwahrscheinlichkeit/);
  assert.match(markup, /Stabilität/);
  assert.match(markup, /Schwierigkeit/);
  assert.match(markup, /Zielerinnerung/);
  assert.match(markup, /Ausschnitt 90–100 %/);
  assert.match(markup, /Zwei diagonale Striche/);
  assert.doesNotMatch(markup, /Vereinfachtes Beispiel/);
  assert.doesNotMatch(markup, /class="[^"]*core-surface-raised[^"]*"[^>]*data-testid="spaced-repetition-visual"/);
  assert.match(markup, /1 · Erste Wiederholung/);
  assert.match(markup, /2 · Wiederholung mit Variante/);
  assert.match(markup, /„Nochmal“, „Schwer“, „Gut“ und „Leicht“ führen gemeinsam betrachtet/);
  assert.match(markup, /Erst dann kommt eine Variante als neuer Punkt hinzu/);
  assert.match(markup, /01 · Erste Wiederholung[\s\S]*02 · Bewertung[\s\S]*03 · Ausreichende Stabilität[\s\S]*04 · D[\s\S]*05 · R[\s\S]*06 · S/);
  assert.doesNotMatch(markup, /Nochmal · S sehr kurz|Schwer · S kurz|Gut · S länger|Leicht · S am längsten/);
  assert.match(markup, /keine garantierte Produktionsschwelle/);
  assert.match(markup, /href="https:\/\/github\.com\/open-spaced-repetition\/awesome-fsrs\/wiki\/ABC-of-FSRS"/);
  assert.equal((markup.match(/xl:sticky/g) ?? []).length, 2);
  assert.equal((markup.match(/data-testid="active-recall-step-/g) ?? []).length, 3);
  assert.equal((markup.match(/data-testid="spaced-repetition-step-/g) ?? []).length, 6);
  assert.equal((markup.match(/data-story-step=/g) ?? []).length, 9);
  assert.equal((markup.match(/data-testid="memory-parameter-/g) ?? []).length, 2);
  assert.equal((markup.match(/data-testid="memory-review-point-/g) ?? []).length, 2);
  assert.equal((markup.match(/data-testid="memory-rating-path-/g) ?? []).length, 4);
  assert.equal((markup.match(/data-testid="memory-y-axis-break"/g) ?? []).length, 1);
});
