import assert from "node:assert/strict";
import test from "node:test";
import type {
  CardVariant,
  Deck,
  DeckSettings,
  LearningItem,
  ReviewRating,
  ReviewState,
} from "./coreTypes.ts";

const now = "2026-07-13T12:00:00.000Z";

const reviewState = {
  id: "state-1",
  learningItemId: "card-1",
  reviewableType: "card",
  reviewableId: "card-1",
  userId: "local-user",
  schedulerVersion: "fsrs_v1",
  state: "new",
  dueAt: now,
  intervalDays: 0,
  ease: 2.5,
  difficulty: 5,
  stability: 0,
  desiredRetention: 0.9,
  retrievability: null,
  reps: 0,
  repetitions: 0,
  lapses: 0,
  maturityXp: 0,
  maturityBand: "new",
  lastReviewedAt: null,
  lastRating: null,
  preferredVariantLevel: 1,
  forcedVariantId: null,
  fallbackUntilCorrect: false,
  lastFailedVariantId: null,
  previousSuccessfulVariantId: null,
  intervalMinutes: null,
  learningStepIndex: 0,
  learningSuccessCount: 0,
  firstLearningAt: null,
  lastLearningStepAt: null,
  graduatedAt: null,
  isGraduated: false,
  sameDaySuccessCount: 0,
  learningDayKey: null,
  schedulerParamsJson: null,
  sourceSchedulerData: null,
} satisfies ReviewState;

const deckSettings = {
  coreMode: "auto",
  appearance: { iconKey: "book-open", iconColor: "#4f5eb1" },
  newCardsPerDay: 20,
  maximumReviewsPerDay: 200,
  newReviewOrder: "reviews-first",
  newCardsTodayOverride: null,
  variantThresholdXp: 121,
  maxActiveVariantsPerCard: 2,
  schedulerProfile: {
    settingsVersion: 2,
    presetId: "standard",
    name: "standard",
    learningStepsMinutes: [5, 15],
    relearningStepMinutes: 5,
    graduatingIntervalDays: 1,
    easyGraduatingIntervalDays: 2,
    easyIntervalDays: 4,
    desiredRetention: 0.9,
    maximumIntervalDays: 36_500,
    lessShortIntervalBias: false,
  },
  aiPolicy: {
    costTier: "balanced",
    allowLocalModels: true,
    allowExternalModels: false,
    maxCostPerJob: 0,
    requireSourceAnchors: true,
    requireHumanApprovalForNewCards: true,
  },
  blacklist: {
    cardTypes: ["image-occlusion"],
    tags: [],
    transforms: [],
    cardIds: [],
    variantIds: [],
  },
} satisfies DeckSettings;

const originalVariant = {
  id: "variant-1",
  learningItemId: "card-1",
  cardId: "card-1",
  sourceCardId: "card-1",
  variantType: "basic",
  variantLevel: 1,
  front: "Frage",
  back: "Antwort",
  explanation: "",
  hintsJson: null,
  answerOptionsJson: null,
  expectedAnswerJson: null,
  generationSource: "original",
  parentVariantId: null,
  anchorVariantId: null,
  isOriginal: true,
  isActive: true,
  transformType: "original",
  transformProfile: {},
  modelRunId: null,
  confidence: 1,
  semanticDelta: "none",
  changedRecognitionCues: [],
  qualityStatus: "active",
  contentHash: "variant_hash",
  sourceAnchors: [],
  reviewState: null,
  performance: {
    id: "performance-1",
    learningItemId: "card-1",
    variantId: "variant-1",
    userId: "local-user",
    attempts: 0,
    reviewCount: 0,
    correctCount: 0,
    wrongCount: 0,
    ratingCounts: { again: 0, hard: 0, good: 0, easy: 0 },
    avgResponseTimeMs: null,
    averageResponseTimeMs: null,
    lastReviewedAt: null,
    lastRating: null,
    localDifficultyEstimate: null,
    masterySignal: null,
    maturityXp: 0,
    createdAt: now,
    updatedAt: now,
  },
  feedback: [],
  versionLog: [],
  createdAt: now,
  updatedAt: now,
  revision: 1,
  deletedAt: null,
  updatedByDeviceId: null,
  meta: {},
} satisfies CardVariant;

const learningItem = {
  id: "card-1",
  noteId: null,
  deckId: "deck-1",
  title: "",
  canonicalQuestion: "Frage",
  canonicalAnswer: "Antwort",
  tags: [],
  concepts: [],
  sourceType: "manual",
  sourceRefId: null,
  source: "manual",
  sourceCardId: null,
  sourceNoteId: null,
  originalFront: "Frage",
  originalBack: "Antwort",
  originalFields: [],
  originalTags: [],
  originalHtml: "Frage<hr>Antwort",
  immutableOriginal: {
    front: "Frage",
    back: "Antwort",
    fields: [],
    html: "Frage<hr>Antwort",
    capturedAt: now,
    source: "manual",
    contentHash: "card_hash",
  },
  mediaRefs: [],
  sourceAnchors: [],
  kind: "basic",
  cardType: "basic",
  draftStatus: "accepted",
  status: "active",
  contentHash: "card_hash",
  learningItemState: reviewState,
  reviewState,
  variants: [originalVariant],
  versionLog: [],
  coreState: {
    isCoreReady: false,
    variantCount: 0,
    lastReviewedAt: null,
    repetitionLevel: 0,
    maturityXp: 0,
    maturityBand: "new",
    eligibility: null,
  },
  createdAt: now,
  updatedAt: now,
  revision: 1,
  deletedAt: null,
  updatedByDeviceId: null,
  meta: {},
} satisfies LearningItem;

const deck = {
  id: "deck-1",
  ownerId: "local-user",
  parentDeckId: null,
  name: "Beispiel",
  description: "",
  source: "manual",
  originalDeckId: null,
  visibility: "private",
  hierarchyPath: ["Beispiel"],
  createdAt: now,
  updatedAt: now,
  revision: 1,
  deletedAt: null,
  updatedByDeviceId: null,
  cardCount: 1,
  tags: [],
  importMeta: {},
  deckSettings,
  sourceDocuments: [],
  cards: [learningItem],
  reviewEvents: [],
  aiJobs: [],
  graph: null,
  communityRefs: [],
  versionLog: [],
} satisfies Deck;

test("führt TypeScript-Tests aus und bildet normalisierte Kernformen ab", () => {
  const rating: ReviewRating = "good";
  assert.equal(deck.cards[0]?.variants[0]?.isOriginal, true);
  assert.equal(deck.deckSettings.coreMode, "auto");
  assert.equal(rating, "good");
});
